name: IMDb Pipeline

on:
  schedule:
    - cron: "30 0 * * *"

  workflow_dispatch:

jobs:
  main:
    name: Run IMDb analysis
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup system dependencies
        run: |
          packages=(
            libcurl4-openssl-dev
            libssl-dev
            libxml2-dev
          )
          sudo apt-get update
          sudo apt-get install --yes "${packages[@]}"

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv

      - name: Setup R dependencies
        uses: r-lib/actions/setup-renv@v2
      
      - name: Run IMDb analysis script
        run: |
          Rscript imdb_analysis_duckdb_version.R
        timeout-minutes: 20
      
      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: imdb-results
          path: app/data/results_with_crew.csv
