name: IMDb Pipeline

on:
  schedule:
    - cron: "30 0 * * *"

  workflow_dispatch:

jobs:
  main:
    name: Run IMDb analysis
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    permissions:
      contents: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup system dependencies
        run: |
          packages=(
            libcurl4-openssl-dev
            libssl-dev
            libxml2-dev
          )
          sudo apt-get update
          sudo apt-get install --yes "${packages[@]}"

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv

      - name: Setup R dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
      
      - name: Install additional packages
        run: |
          R -e 'if(!requireNamespace("duckdb", quietly = TRUE)) install.packages("duckdb")'
          R -e 'if(!requireNamespace("duckplyr", quietly = TRUE)) install.packages("duckplyr")'
          R -e 'if(!requireNamespace("tidyr", quietly = TRUE)) install.packages("tidyr")'
          R -e 'renv::status()'
      
      - name: Run IMDb analysis script with debugging
        run: |
          Rscript -e "options(error = function() { traceback(2); quit(status = 1) })" imdb_analysis_duckdb_version.R
        timeout-minutes: 15
      
      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: imdb-results
          path: app/data/results_with_crew.csv
        if: always()

      - name: Commit results to repository
        if: success()
        run: |
          git config --local user.email "tiagoadrianunes@gmail.com"
          git config --local user.name "TiagoAdriaNunes"
          git add app/data/results_with_crew.csv
          git commit -m "Update IMDb analysis results [skip ci]" || echo "No changes to commit"
          git push
