name: IMDb Pipeline

on:

  schedule:
    - cron: "30 0 * * *"

  workflow_dispatch:

jobs:
  run-imdb-script:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
      
      - name: Install R packages
        run: |
          Rscript -e 'if (!requireNamespace("duckdb", quietly = TRUE)) install.packages("duckdb", repos="https://cloud.r-project.org")'
          Rscript -e 'if (!requireNamespace("duckplyr", quietly = TRUE)) install.packages("duckplyr", repos="https://cloud.r-project.org")'
          Rscript -e 'if (!requireNamespace("tidyr", quietly = TRUE)) install.packages("tidyr", repos="https://cloud.r-project.org")'
        timeout-minutes: 30
      
      - name: Run IMDb analysis script
        run: |
          Rscript imdb_analysis_duckdb_version.R
        timeout-minutes: 15
      
      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: imdb-results
          path: app/data/results_with_crew.csv
